services:
  auth-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_USER: ${AUTH_DB_USER} 
      POSTGRES_DB: ${AUTH_DB_NAME} 
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - custom
  
  test-auth-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_USER: ${AUTH_DB_USER} 
      POSTGRES_DB: ${AUTH_DB_NAME} 
    ports:
      - "5434:5432"
    networks:
      - custom

volumes:
  auth-postgres-data:

networks:
  custom:
    driver: bridge